import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const proxy = process.env.HTTPS_PROXY || process.env.https_proxy;
console.log('proxy env =', proxy);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', proxy: proxy ? { server: proxy } : undefined });
const ctx = await b.newContext();
const p = await ctx.newPage();
p.on('console', m => console.log('[console]', m.type(), m.text().slice(0,200)));
const r = await p.goto('https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400&display=swap', { waitUntil: 'load', timeout: 20000 }).catch(e => { console.log('ERR', e.message.slice(0,300)); return null; });
if (r) console.log('status', r.status(), (await r.text()).slice(0,200));
await b.close();
